### ISSUE TITLE
Laravel 5.4 Version Support

### ISSUE THREAD

**Issue by HDVinnie** [artdarek/toastr#2]
Does this work with Laravel 5.4?

**Comment by artdarek** [comment]
Hi, I fixed all compatibility issues and now it should be fine.
Use version "2.0.*" in your composer.json file.

```
"require": {
  "artdarek/toastr": "2.0.*"
}
```

**Comment by HDVinnie** [comment]
Installed as said in readme using version 2.0. 

added Toastr Service Provider and alias to app/config. added the @include('toastr::alerts') to my default.blade.php. added alert into my usercontroller like so.

```
 public function login()
    {
        if (Request::isMethod('post')) {
            $input = Request::all();
            if (Auth::attempt(['username' => $input['username'], 'password' => $input['password']])) {
            Toastr::success('Welcome back!')->push();
                return Redirect::intended('/');
            } else {
                Toastr::danger('Whoops','Username or Password is invalid!')->push();
            }
        }
        return view('user.login');
    }
```

And I get following error.

FatalThrowableError in UserController.php line 82:
Class 'App\Http\Controllers\Toastr' not found

**Comment by artdarek** [comment]
At the top of your UserController.php add:

```
use \Toastr;
```
